const BACKEND_API_BASE = process.env.REACT_APP_BACKEND_API_BASE || "http://localhost:9000/api";
const STACKOVERFLOW_URL_PATTERN = process.env.REACT_APP_STACKOVERFLOW_URL_PATTERN || "stackoverflow.com";
const CONFLUENCE_URL_PATTERN = process.env.REACT_APP_CONFLUENCE_URL_PATTERN || "http://localhost:8090/";

export { BACKEND_API_BASE, STACKOVERFLOW_URL_PATTERN, CONFLUENCE_URL_PATTERN };
